### ISSUE TITLE
Custom name

### ISSUE THREAD

**Issue by goodmind** [janestreet/ppx_fields_conv#5]
Support custom names for fields?

**Comment by sliquister** [comment]
Are you talking about the `Fields` module, are you saying you want values generate for field `a` to not generate labels `~a` but instead some other label?

Either way, what's the motivation for this? If the former, it's possible to simply write `module Xyz = Fields` after the `@@deriving`.

**Comment by sliquister** [comment]
I'm going to close this, as this not really actionable given the lack of response (of course the lack of response is in large part due to the fact that we took forever to respond, but the people that get notified when issues are reported are now more relevant and numerous, so new issues will presumably not suffer such a fate).
