### ISSUE TITLE
Feature request: custom module

### ISSUE THREAD

**Issue by Pitometsu** [janestreet/ppx_fields_conv#6]
Is it possible to have generated fields at custom module like:

```ocaml
module M = struct
  type a = { x : int; y : int }
  [@@deriving fields: GetA]

  type b = { x : int; y : int }
  [@@deriving fields: GetB]
end

let f : M.b = let f : M.a = { x = 42; y = 42 } in
  { M.b.x = [%fields_module M.a].x f
  ; M.b.y = [%fields_module M.a].y f }
```

**Comment by sliquister** [comment]
This `[%fields_module: ..]` is not implementable, as it would be require `deriving fields` to be in the same file as `[%fields_module: ..]`, and computing scoping which can't be done in a ppx.

Are you saying that, for:

```ocaml
type a = { x : int; y : int }
[@@deriving fields GetA]
```

ppx_fields_conv would generate

```ocaml
module GetA : sig
  val x : a -> int
  val y : a -> int
  module Fields_of_a : sig ... more things ... end
end
```
?

Technically, this would be easy, but the value seems marginal? Can't you just do this:

```ocaml
module M = struct
  module A = struct
    type t = { x : int; y : int }
    [@@deriving fields]
  end
  module B = struct
    type t = { x : int; y : int }
    [@@deriving fields]
  end
  type a = A.t
  type b = B.t
end

let f : M.b =
  let f : M.a = { x = 42; y = 42 } in
  { x = M.A.x f
  ; y = M.A.y f }
```

**Comment by sliquister** [comment]
I'm going to close this, as this is old and it's not clear if the reporter still wants this and if so, why my suggestion wouldn't be enough.

That being said, the people that get notified when issues are reported are now more relevant and numerous, so new issues should be much more likely to be discussed/clarified at the time they get reported, instead of way later when the motivation may be gone.
